Repository idefix-code/idefix, pull requests merged in 2024-11, with the labels that each got.

#293 fix MakeVsFromAmag in spherical-non axisymmetric runs
  src/dataBlock/dataBlockHost.cpp
Labels: bug

#294 TST: handle a deprecation warning from numpy 1.25
  test/MHD/AmbipolarCshock/python/testidefix.py
  test/MHD/AmbipolarCshock3D/python/testidefix.py
Labels: cleanup, tests

#292 ENH: write and read native coordinates in VTK
  pytools/vtk_io.py
  src/output/vtk.cpp
  src/output/vtk.hpp
Labels: enhancement
