Repository idefix-code/idefix, pull requests merged in 2025-02, with the labels that each got.

#308 Add a class to compute accelerated cumulative sum
  .github/workflows/idefix-ci-jobs.yml
  doc/source/faq.rst
  src/utils/CMakeLists.txt
  src/utils/column.cpp
  src/utils/column.hpp
  test/utils/columnDensity/definitions.hpp
  test/utils/columnDensity/idefix.ini
  test/utils/columnDensity/setup.cpp
  test/utils/columnDensity/testme.py
Labels: enhancement

#317 Implement Collisionless heat flux into the Braginskii module
  doc/source/modules/braginskii.rst
  src/fluid/braginskii/bragThermalDiffusion.cpp
  src/fluid/braginskii/bragThermalDiffusion.hpp
  src/fluid/braginskii/bragViscosity.cpp
  src/fluid/braginskii/bragViscosity.hpp
  src/fluid/fluid_defs.hpp
  test/MHD/MTI/idefix-rkl.ini
  test/MHD/MTI/idefix-sl.ini
  test/MHD/MTI/idefix.ini
  test/MHD/MTI/setup.cpp
  test/MHD/clessTDiffusion/CMakeLists.txt
  test/MHD/clessTDiffusion/definitions.hpp
  test/MHD/clessTDiffusion/idefix.ini
  test/MHD/clessTDiffusion/python/testidefix.py
  test/MHD/clessTDiffusion/setup.cpp
  test/MHD/clessTDiffusion/testme.py
  test/MHD/sphBragTDiffusion/idefix.ini
Labels: new feature

#318 add global routines to dump Idefix arrays to disk
  doc/source/programmingguide.rst
  src/global.hpp
Labels: enhancement

#323 fix RKL in grids with small spacing
  src/fluid/calcRightHandSide.hpp
  src/rkl/rkl.hpp
Labels: bug
